SteelStudio.Web/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using SteelStudio.Common.Models;
using SteelStudio.Web.Models;

namespace SteelStudio.Web.Controllers
{
    [Authorize (Roles = "administrador")]
    public class CategoriesController : Controller
    {
        private LocalDataContext db = new LocalDataContext();

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create(int id = 0)
        {
            if (id == 1)
                ViewBag.Creado = "Y";
            else
            {
                if (id == 2)
                    ViewBag.Creado = "E";
                else
                    ViewBag.Creado = "N";
            }            
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryId,Initials,Description")] Category category)
        {
            if (ModelState.IsValid)
            {
                var cat = (from c in db.Categories.AsEnumerable()
                             where c.Description == category.Description                             
                             select c).SingleOrDefault();
                if (cat == null)
                {
                    db.Categories.Add(category);
                    db.SaveChanges();
                    return RedirectToAction("Create", new { id = 1 });
                }
                else
                    return RedirectToAction("Create", new { id = 2 });
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }           

            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryId,Initials,Description")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");                
            }
            return View(category);
        }        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(FormCollection result)
        {
            if (result["Id[]"] != null)
            {
                string[] items = result["Id[]"].Split(',');
                foreach (var id in items)
                {
                    Category category = db.Categories.Find(Convert.ToInt32(id));
                    if (category != null)
                    {
                        db.Categories.Remove(category);
                    }
                }
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult DeleteOne(int id)
        {
            Category category = db.Categories.Find(id);
            if (category != null)
            {
                db.Categories.Remove(category);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SteelStudio.Web/Controllers/DesktopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SteelStudio.Web.Controllers
{
    public class DesktopController : Controller
    {
        // GET: Desktop
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public ActionResult _MenuPartialView()
        {            
            return PartialView();
        }
    }
}

SteelStudio.Web/Controllers/ProductsController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SteelStudio.Common.Models;
using SteelStudio.Web.Helpers;
using SteelStudio.Web.Models;

namespace SteelStudio.Web.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private LocalDataContext db = new LocalDataContext();

        // GET: Products
        public async Task<ActionResult> Index()
        {
            return View(await db.Products.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create(int id = 0)
        {
            if (id == 1)
                ViewBag.Creado = "Y";
            else
            {
                if (id == 2)
                    ViewBag.Creado = "E";
                else
                    ViewBag.Creado = "N";
            }

            List<Category> categories_list = new List<Category>();            
            categories_list.AddRange(db.Categories.ToList());            
            ViewBag.categories = categories_list;
            CreateProductModel model = new CreateProductModel();

            return View(model);            
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateProductModel productModel)
        {
            if (ModelState.IsValid)
            {
                var prod = (from p in db.Products.AsEnumerable()
                           where p.Code == productModel.Code
                           select p).SingleOrDefault();
                if (prod == null)
                {
                    var product = this.ToProduct(productModel);
                    if (productModel.CategoryId != 0)
                        product.Category = db.Categories.Find(productModel.CategoryId);

                    var pic = string.Empty;
                    var folder = "~/Content/Images/Products";

                    //verifico que se haya seleccionado una foto como foto principal
                    if (productModel.ImageFile != null) 
                    {
                        pic = FileHelper.UploadPhoto(productModel.ImageFile, folder);
                        pic = $"{folder}/{pic}";

                        List<ProductImage> list = new List<ProductImage>();
                        ProductImage productImage = new ProductImage()
                        {
                            ImageUrl = pic,        
                            //Product = product,
                        };
                        list.Add(productImage);

                        product.ProductImage = list;
                    }
                    
                    db.Products.Add(product);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Create", new { id = 1 });
                }
                else
                    return RedirectToAction("Create", new { id = 2 });
            }

            return View(productModel);
        }

        private Product ToProduct(CreateProductModel view)
        {
            return new Product
            {
                Code = view.Code,
                Notes = view.Notes,
                UserName = User.Identity.GetUserName(),
            };
        }

        private Product ToProduct(EditProductModel view)
        {
            return new Product
            {
                ProductId = view.ProductId,
                Code = view.Code,
                Notes = view.Notes,
                Category = db.Categories.Find(view.CategoryId),
                UserName = view.UserName,                
            };
        }

        // GET: Products/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            EditProductModel model = new EditProductModel();
            model.ProductId = product.ProductId;
            model.Code = product.Code;
            model.CategoryId = product.Category.CategoryId;
            model.UserName = product.UserName;
            model.Notes = product.Notes;
            model.ProductImage = product.ProductImage;
            model.ImageFullPath = product.ImageFullPath;

            List<Category> categories_list = new List<Category>();
            categories_list.AddRange(db.Categories.ToList());
            ViewBag.categories = categories_list;

            return View(model);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditProductModel model)
        {
            if (ModelState.IsValid)
            {
                var product = db.Products.Find(model.ProductId);

                //var product = this.ToProduct(model);            

                product.Code = model.Code;
                product.Notes = model.Notes;
                product.Category = db.Categories.Find(model.CategoryId);

                //db.Entry(product).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Edit", model.ProductId);
        }

        // GET: Products/UploadImages/5
        public async Task<ActionResult> UploadImages(int? id, int error = 0)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            if (error == 1)
                ViewBag.Creado = "Y";
            else
            {
                if (error == 2)
                    ViewBag.Creado = "E";
                else
                    ViewBag.Creado = "N";
            }

            UploadImagesProductModel model = new UploadImagesProductModel();
            model.ProductId = product.ProductId;
            model.Code = product.Code;
            model.CategoryDescription = product.Category.Description;
            model.ProductImage = product.ProductImage;
            model.ImageFullPath = product.ImageFullPath;

            return View(model);
        }

        // POST: Products/UploadImages/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UploadImages(UploadImagesProductModel model)
        {
            if (ModelState.IsValid)
            {
                var product = db.Products.Find(model.ProductId);

                var pic = string.Empty;
                var folder = "~/Content/Images/Products";

                //verifico que se haya seleccionado una foto como foto principal
                if (model.ImageFile != null)
                {
                    pic = FileHelper.UploadPhoto(model.ImageFile, folder);
                    pic = $"{folder}/{pic}";
                    
                    ProductImage productImage = new ProductImage()
                    {
                        ImageUrl = pic,
                        //Product = product,
                    };
                   
                    product.ProductImage.Add(productImage);
                }

                await db.SaveChangesAsync();
                return RedirectToAction("UploadImages", new { id = model.ProductId, error = 1 });
            }
            return RedirectToAction("UploadImages", new { id = model.ProductId, error = 2 });
        }

        // GET: Products/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Product product = await db.Products.FindAsync(id);
            //var list_images = product.ProductImage;
            ProductImage[] list_images = new ProductImage[product.ProductImage.Count];
            product.ProductImage.CopyTo(list_images, 0);
            db.Products.Remove(product);
            await db.SaveChangesAsync();

            //-----------trato de eliminar los ficheros de las imagenes de ese producto-----------//
            try
            {

SteelStudio.Web/Views/Categories/Create.cshtml
@model SteelStudio.Common.Models.Category

@{
    ViewBag.Title = "Crear nueva categoria";
    Layout = "~/Views/Shared/_LayoutDesktop.cshtml";
}

<div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="icon-home"></i>
                @Html.ActionLink("Escritorio", "Index", "Desktop")
            </li>
            <li>
                <i class="icon-trello"></i>
                @Html.ActionLink("Categorias", "Index", "Categories")
            </li>
            <li class="active">Crear categoria</li>
        </ul><!--.breadcrumb-->
</div>

<div class="page-content">
    <div class="row-fluid">
        <div class="span12">
            <div class="space-6"></div>
            @if (ViewBag.Creado == "Y")
            {
                <div class="alert alert-block alert-success">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>
                    <i class="icon-ok green"></i>
                    <strong class="green">
                        Se ha creado correctamente la categoria.
                    </strong>

                </div>

            }
            @if (ViewBag.Creado == "E")
            {
                <div class="alert alert-block alert-warning">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>
                    <i class="icon-ok red"></i>
                    <strong class="red">
                        La categoria ya se encuentra, no pudo ser agregada.
                    </strong>
                </div>

            }

            <div class="row-fluid">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Crear nueva categoria</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Initials, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Initials, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Initials, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Crear" class="btn btn-primary" />
                                &nbsp;
                                @Html.ActionLink("Atrás", "Index", new { }, new { @class = "btn btn-success" })
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

SteelStudio.Web/Views/Categories/Details.cshtml
@model SteelStudio.Common.Models.Category

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutDesktop.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Initials)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Initials)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CategoryId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SteelStudio.Web/Views/Categories/Edit.cshtml
@model SteelStudio.Common.Models.Category

@{
    ViewBag.Title = "Editar categoria";
    Layout = "~/Views/Shared/_LayoutDesktop.cshtml";
}

<div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="icon-home"></i>
                @Html.ActionLink("Escritorio", "Index", "Desktop")
            </li>
            <li>
                <i class="icon-trello"></i>
                @Html.ActionLink("Categorias", "Index", "Categories")
            </li>
            <li class="active">Editar categoria</li>
        </ul><!--.breadcrumb-->
</div>

<div class="page-content">
    <div class="row-fluid">
        <div class="span12">
            <div class="space-6"></div>            
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Edición de la categoria</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.CategoryId)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Initials, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Initials, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Initials, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Actualizar" class="btn btn-primary" />
                            &nbsp;
                            @Html.ActionLink("Atrás", "Index", new { }, new { @class = "btn btn-success" })
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

SteelStudio.Web/Views/Categories/Index.cshtml
@model IEnumerable<SteelStudio.Common.Models.Category>

@{
    ViewBag.Title = "Categorias";
    Layout = "~/Views/Shared/_LayoutDesktop.cshtml";
}

<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            @Html.ActionLink("Escritorio", "Index", "Desktop")
        </li>
        <li class="active">Categorias</li>
    </ul><!--.breadcrumb-->
</div>
<div class="page-content">
    <p class="text-success">@ViewBag.StatusMessage</p>
    <h4>Gestión de categorias</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Categorias:</dt>
        <dd>
            [
            @Html.ActionLink("Crear nueva categoria", "Create", "Categories")
            ]
        </dd>
    </dl>
    <hr />
    @using (Html.BeginForm("Index", "Categories", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="row-fluid">
            <div class="table-header">
                @*<button class="btn btn-small btn-primary" type="submit" name="Delete" formaction="@Url.Action("Delete")" formmethod="post" onclick="return confirm('¿Desea eliminar las categorias seleccionadas?');">  Eliminar seleccionados </button>*@
                Listado de categorias
            </div>
            <div class="space">
                <div class="pull-right tableTools-container"></div>
            </div>
            <table id="dynamic-table" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th @*class="center"*@>
                            @*<label class="pos-rel">
                                    <input type="checkbox" class="ace" />
                                    <span class="lbl"></span>
                                </label>*@
                        </th>
                        <th style="width: 20%">
                            Sigla
                        </th>
                        <th style="width: 57%">
                            Descripción
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var category in Model)
                    {
                        <tr>
                            <td class="center">
                                @*<label class="pos-rel">
                                        <input type="checkbox" class="ace" name="Id[]" value="@category.CategoryId" />
                                        <span class="lbl"></span>
                                    </label>*@
                                @if (category.Product.Count != 0)
                                {
                                    <img src="~/Content/Images/open.png" />
                                }
                                else
                                {
                                    <img src="~/Content/Images/open_blocked.png" />
                                }
                                <div style="display:none">
                                    <table class="table table-striped table-bordered">
                                        <tr>
                                            <th style="width: 10%">Código</th>
                                            <th style="width: 40%">Observaciones</th>
                                            <th style="width: 30%">Creado por</th>
                                            <th></th>
                                        </tr>
                                        @foreach (var product in category.Product)
                                        {
                                            <tr>
                                                <td>@Html.DisplayFor(modelItem => product.Code)</td>
                                                <td>@Html.DisplayFor(modelItem => product.Notes)</td>
                                                <td>@Html.DisplayFor(modelItem => product.UserName)</td>
                                                <td>
                                                    @Html.ActionLink("Detalles", "Details", "Products", new { id = product.ProductId }, null)
                                                </td>
                                            </tr>
                                        }
                                    </table>
                                </div>
                            </td>
                            <td class="">
                                @Html.DisplayFor(modelItem => category.Initials)
                            </td>
                            <td class="hidden-480">
                                @Html.DisplayFor(modelItem => category.Description)
                            </td>
                            <td>
                                @Html.ActionLink("Editar", "Edit", new { id = category.CategoryId }) |
                                @Html.ActionLink("Eliminar", "DeleteOne", new { id = category.CategoryId })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
</div>

@section scripts {
    <script type="text/javascript">
        $(function () {
            var oTable1 = $('#dynamic-table').dataTable({
                "aoColumns": [
                    { "bSortable": false }, null, null, { "bSortable": false }
                ]
            });

            //And for the first simple table, which doesn't have TableTools or dataTables
            //select/deselect all rows according to table header checkbox
            var active_class = 'active';
            $('#dynamic-table > thead > tr > th input[type=checkbox]').eq(0).on('click', function () {
                var th_checked = this.checked;//checkbox inside "TH" table header

                $(this).closest('table').find('tbody > tr').each(function () {
                    var row = this;
                    if (th_checked) $(row).addClass(active_class).find('input[type=checkbox]').eq(0).prop('checked', true);
                    else $(row).removeClass(active_class).find('input[type=checkbox]').eq(0).prop('checked', false);
                });
            });

            //select/deselect a row when the checkbox is checked/unchecked
            $('#dynamic-table').on('click', 'td input[type=checkbox]', function () {
                var $row = $(this).closest('tr');
                if ($row.is('.detail-row ')) return;
                if (this.checked) $row.addClass(active_class);
                else $row.removeClass(active_class);
            });
            //Assign Click event to Plus Image.
            $("body").on("click", "img[src*='open.png']", function () {
                $(this).closest("tr").after("<tr><td></td><td colspan = '999'>" + $(this).next().html() + "</td></tr>");
                $(this).attr("src", "Content/Images/close.png");
            });
            //Assign Click event to Minus Image.
            $("body").on("click", "img[src*='close.png']", function () {
                $(this).attr("src", "Content/Images/open.png");
                $(this).closest("tr").next().remove();
            });
        });

    </script>
}